'use client'

import { useEffect, useState } from 'react'
import { Activity, ArrowLeft, Check, ChevronRight, CircleHelp, Clock3, Database, FileText, Globe2, History, LayoutDashboard, Menu, MoreHorizontal, Network, Play, Plus, Search, Settings2, ShieldCheck, Sparkles, X } from 'lucide-react'

const API_BASE = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000').replace(/\/$/, '')

function request(path, options) {
  if (!API_BASE) throw new Error('Set VITE_API_BASE_URL to your Express API URL.')
  return fetch(`${API_BASE}${path}`, options).then(async (response) => {
    const body = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(body.message || body.error || `Request failed (${response.status})`)
    return body
  })
}
function unwrap(body) { return body?.data ?? body?.result ?? body }
function resultRows(body) {
  const value = unwrap(body)
  if (Array.isArray(value)) return value
  return value?.results || value?.scrapedData || value?.data || []
}
function Nav({ icon, text, active, onClick = () => {}, accent }) { return <button className={`nav-item ${active ? 'active' : ''} ${accent ? 'accent' : ''}`} onClick={onClick}>{icon}<span>{text}</span></button> }
function Shell({ active, children, navigate }) { return <div className="cx-shell"><aside className="cx-sidebar"><div className="cx-brand"><span className="brand-mark"><Network size={17} /></span>crawl<span className="lime">x</span></div><div className="workspace"><div className="workspace-icon">A</div><div><b>Acme workspace</b><small>Personal workspace</small></div><ChevronRight size={15} /></div><nav><div className="nav-label">Workspace</div><Nav icon={<LayoutDashboard />} text="Overview" active={active === 'new'} onClick={() => navigate('new')} /><Nav icon={<Plus />} text="New crawl" active={active === 'new'} onClick={() => navigate('new')} accent /><Nav icon={<History />} text="Crawl history" active={active === 'history'} onClick={() => navigate('history')} /></nav><div className="sidebar-bottom"><Nav icon={<CircleHelp />} text="Help center" /><Nav icon={<Settings2 />} text="Settings" /><div className="user"><div className="avatar">JD</div><div><b>Jordan Davis</b><small>jordan@acme.co</small></div><MoreHorizontal size={16} /></div></div></aside><main className="cx-main"><header className="topbar"><button className="menu"><Menu size={20} /></button><div className="crumb">Workspace <ChevronRight size={14} /> <b>{active === 'crawl' ? 'Crawl session' : 'New crawl'}</b></div><span className="api-pill"><span className="online-dot" /> {API_BASE ? 'API connected' : 'API not configured'}</span></header><section className="content">{children}</section></main></div> }
function Title({ eyebrow, title, desc, action }) { return <div className="section-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{action}</div> }
function Status({ status }) { return <span className={`status ${status}`}><span className="status-dot" />{status}</span> }

function NewCrawl({ started }) {
  const [url, setUrl] = useState(''), [depth, setDepth] = useState(2), [same, setSame] = useState(true), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  async function submit(event) { event.preventDefault(); setError(''); try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('Enter a valid HTTP or HTTPS URL.'); if (depth < 0 || depth > 10) throw new Error('Depth must be between 0 and 10.'); setLoading(true); const data = unwrap(await request('/api/crawl', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ startUrl: url, maxDepth: Number(depth), sameDomainOnly: same }) })); const id = data._id || data.id || data.crawlId; if (!id) throw new Error('The API did not return a crawl id.'); started(id) } catch (e) { setLoading(false); setError(e.message) } }
  return <><Title eyebrow="Crawler" title="Start a new crawl" desc="Extract structured data from any website with precision." /><div className="new-grid"><form className="panel form-panel" onSubmit={submit}><div className="panel-heading"><div className="panel-icon lime-icon"><Globe2 size={19} /></div><div><h2>Crawl configuration</h2><p>Settings are sent directly to your Express crawler.</p></div></div><label>Target URL<span className="required">*</span><div className="input-wrap"><Globe2 size={17} /><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com" /></div></label>{error && <div className="error"><X size={15} />{error}</div>}<div className="form-row"><label>Max depth<div className="input-wrap"><input className="number" type="number" min="0" max="10" value={depth} onChange={(e) => setDepth(Number(e.target.value))} /><span className="suffix">levels</span></div></label><div className="toggle-field"><span>Same-domain only</span><small>Only follow links on this domain</small><button type="button" className={`toggle ${same ? 'on' : ''}`} onClick={() => setSame(!same)}><span /></button></div></div><div className="form-footer"><span className="secure"><ShieldCheck size={15} /> Crawl stays private</span><button className="primary-button" disabled={loading}>{loading ? 'Starting…' : <><Play size={16} /> Start crawl</>}</button></div></form><div className="info-card"><div className="spark"><Sparkles size={18} /></div><h3>Live extraction</h3><p>Results come from your configured backend, not demo records.</p><span><FileText size={15} /> Titles, headings, metadata & links</span></div></div></>
}
function Metric({ icon, label, value, green, red }) { return <div className="metric panel"><div className={`metric-icon ${green ? 'green' : ''} ${red ? 'red' : ''}`}>{icon}</div><div><small>{label}</small><b>{value}</b></div></div> }
function CrawlView({ id, back }) {
  const [crawl, setCrawl] = useState(null), [rows, setRows] = useState([]), [query, setQuery] = useState(''), [error, setError] = useState('')
  async function load() { try { const [c, r] = await Promise.all([request(`/api/crawls/${id}`), request(`/api/results?crawlId=${encodeURIComponent(id)}`)]); const crawlData = unwrap(c); setCrawl(crawlData?.crawl || crawlData); setRows(resultRows(r)) } catch (e) { setError(e.message) } }
  useEffect(() => { load(); const timer = setInterval(() => { if (!crawl || !['completed', 'failed'].includes(crawl.status)) load() }, 2500); return () => clearInterval(timer) }, [id, crawl?.status])
  const filtered = rows.filter((r) => (r.url || '').includes(query) || (r.title || '').toLowerCase().includes(query.toLowerCase()))
  if (error) return <div className="error">{error}</div>
  return <><button className="back-link" onClick={back}><ArrowLeft size={15} /> Back</button><Title eyebrow={`Crawl session / ${id}`} title={crawl?.startUrl || crawl?.url || 'Loading crawl…'} desc={crawl ? `${crawl.pagesCrawled || crawl.pages || 0} pages processed` : 'Fetching live crawl status'} action={crawl && <Status status={crawl.status} />} /><div className="metrics"><Metric icon={<Database />} label="Pages discovered" value={crawl?.visited?.length || crawl?.pagesDiscovered || 0} /><Metric icon={<Check />} label="Pages crawled" value={crawl?.pagesCrawled || 0} green /><Metric icon={<X />} label="Pages failed" value={crawl?.pagesFailed || 0} red /><Metric icon={<Clock3 />} label="Queue size" value={crawl?.queue?.length || 0} /></div><div className="progress-panel panel"><div className="progress-head"><div><h2>{crawl?.status === 'completed' ? 'Crawl completed' : 'Crawl in progress'}</h2><p>Polling the backend every 2.5 seconds for fresh extracted pages.</p></div><Activity size={20} /></div></div><div className="results-heading"><div><div className="eyebrow">Extracted data</div><h2>Pages in this crawl <span>{rows.length}</span></h2></div><div className="search small-search"><Search size={15} /><input placeholder="Search results…" value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><div className="panel table-panel"><table><thead><tr><th>URL</th><th>TITLE</th><th>CRAWLED AT</th></tr></thead><tbody>{filtered.map((r) => <tr key={r._id || r.id}><td>{r.url}</td><td>{r.title || 'Untitled page'}</td><td>{r.crawledAt ? new Date(r.crawledAt).toLocaleString() : '—'}</td></tr>)}</tbody></table></div></>
}
export default function Page() { const [view, setView] = useState('new'), [crawlId, setCrawlId] = useState(''); return <Shell active={view} navigate={setView}>{view === 'new' ? <NewCrawl started={(id) => { setCrawlId(id); setView('crawl') }} /> : <CrawlView id={crawlId} back={() => setView('new')} />}</Shell> }
